use_frameworks!

platform :ios, '9.0'

target 'WXCustomerServiceLib_Example' do
  pod 'WXCustomerServiceLib', :path => '../'

  target 'WXCustomerServiceLib_Tests' do
    inherit! :search_paths

    
  end
end
